title: basti.space
feed-title: Basti Tee's blog
feed-description: The happiness of pursuit
email: basti.tee@gmx.de
url: "https://basti.space"
# url: http://localhost:8000
github_username:  bastitee
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
exclude:
  - README
  - "*.sh"
